/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: please check correctness of conversion of '=>' in arrays by hand

---------------------------- */

// globals
var undefined;


function calculate () {
	var options = "";
	var prompt = "";
	// most options should only be shown, if they differ from the default.
	options = "";
	if (getValue ("echo")) {
		options += ", echo=TRUE";
		prompt = getValue ("promptecho");
		if (!empty (prompt)) {
			options += ", prompt.echo=\"" + prompt + "\"";
		}
		options += ", max.deparse.length=" + getValue ("maxdeparselength");
		options += ", verbose=" + getValue ("verbose");
	} else {
		options += ", verbose=FALSE";
	}
	options += ", print.eval=" + getValue ("printeval");

	echo ('source (file="' + getValue("file") + '", local=' + getValue("local") + options + ', chdir=' + getValue("chdir") + ')\n');
}

function printout () {
	makeHeadercode ("Source R file", new Array("File" ,  getValue ("file")));
}


