# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

# Temporary workaround: Require kate master version, while default target (24.05) is not buildable outside Linux due to dbus breakage
# Temporary workardoun: Require kconfig master version, while default target (6.3.0) fails to build (test) in AppImage builds more often than not
[BlueprintSettings]
kde/applications/kate.version=master
kde/frameworks/tier1/kconfig.defaultTarget=master
