# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/cppcheck.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/craft-appimage-qt6.yml
      - /gitlab-templates/craft-windows-x86-64-qt6.yml
      - /gitlab-templates/craft-macos-arm64-qt6.yml
      - /gitlab-templates/craft-macos-x86-64-qt6.yml
#      - /gitlab-templates/flatpak.yml // just a waste of CPU power in the current state

clang_format:
  stage: build
  image: debian:stable
  tags:
    - Linux
  only:
    - merge_requests
    - master
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends git clang-format-19
  script:
    - find rkward \( -name "*.cpp" -or -name "*.h"  -or -name "*.js" \) -exec clang-format-19 -i {} \;
    - git diff --exit-code

# setup mix-and-matched from okular, removing some extras
# combined check for building on "old" distribution (should ideally be previous ubuntu LTS, but 24.10 is the first to contain KF6, so using that)
build_clazy_ubuntu_24_10:
  stage: build
  image: ubuntu:24.10
  tags:
    - Linux
  only:
    - merge_requests
  variables:
    #CLAZY_CHECKS: level0,level1,level2,no-ctor-missing-parent-argument,isempty-vs-count,qhash-with-char-pointer-key,raw-environment-function,qproperty-type-mismatch
    CXXFLAGS: -Werror -Wno-deprecated-declarations
    CC: clang
    CXX: clazy
  before_script:
    - sed -i 's/ deb/ deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
    - sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/' /etc/apt/sources.list.d/ubuntu.sources
    - sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/' /etc/apt/sources.list.d/ubuntu.sources
    - apt-get update
    - apt-get install --yes eatmydata
    - eatmydata apt-get install --yes --no-install-recommends clazy
    # rkward build deps:
    - eatmydata apt-get install --yes --no-install-recommends cmake extra-cmake-modules pkg-kde-tools debhelper qt6-webengine-dev libkf6notifications-dev gettext libkf6coreaddons-dev libkf6crash-dev libkf6guiaddons-dev libkf6i18n-dev libkf6iconthemes-dev libkf6breezeicons-dev libkf6texteditor-dev libkf6textwidgets-dev libkf6windowsystem-dev libkf6xmlgui-dev pkgconf r-base-dev
  script:
    - mkdir -p build && cd build
    - cmake ..
    - CLAZY_IGNORE_DIRS="3rdparty" make -j 5
  artifacts: null
