# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/cppcheck.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/craft-appimage-qt6.yml
      - /gitlab-templates/craft-windows-x86-64-qt6.yml
      - /gitlab-templates/craft-macos-arm64-qt6.yml
      - /gitlab-templates/craft-macos-x86-64-qt6.yml
#      - /gitlab-templates/flatpak.yml // just a waste of CPU power in the current state

clang_format:
  stage: build
  image: debian:stable
  tags:
    - Linux
  only:
    - merge_requests
    - master
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends git clang-format-19
  script:
    - find rkward \( -name "*.cpp" -or -name "*.h"  -or -name "*.js" \) -exec clang-format-19 -i {} \;
    - git diff --exit-code
