# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
  tests-load-sensitve: True
  per-test-timeout: 180
  cppcheck-arguments: '--enable=warning,style,performance --inline-suppr -DR_EXECUTABLE=\"/usr/bin/R\" -DRKWARD_VERSION=\"dummy\" -DCPPCHECK_ONLY=1'
