/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;


function calculate () {
	var vars = "";
	var intercept = "";
	vars = str_replace ("\n", " + ", trim (getValue ("x")));
	if (!getValue ("intercept.state.numeric")) intercept = "0 + ";

	echo ('results <- summary.lm (lm (' + getValue ("y") + ' ~ ' + intercept + vars + '))\n');
}

function printout () {
	echo ('rk.header ("Linear Regression")\n');
	echo ('rk.print(results)\n');
}

