/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var nAvg;
var nDist;
var undefined;

include ('plot_clt_common.js');

function doParameters () {
	echo ('mean <- ' + getValue ("mean") + '; sd <- ' + getValue ("sd") + ';\n');
}

function doExpVar () {
	echo ('avg.exp <- exp(mean+sd^2/2);\n');
	echo ('avg.var <- (exp(2*mean+sd^2)*(exp(sd^2)-1))/' + nAvg + ';\n');
}

function doGenerateData () {
	echo ('data <- matrix(rlnorm(n=' + nAvg*nDist + ', meanlog=mean, sdlog=sd), nrow=' + nAvg + ');\n');
}

