/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var nAvg;
var nDist;
var undefined;

include ('plot_clt_common.js');

function doParameters () {
	echo ('rate <- ' + getValue ("rate") + ';\n');
}

function doExpVar () {
	echo ('avg.exp <- 1/rate;\n');
	echo ('avg.var <- (1/(rate^2))/' + nAvg + ';\n');
}

function doGenerateData () {
	echo ('data <- matrix(rexp(n=' + nAvg*nDist + ', rate=rate), nrow=' + nAvg + ');\n');
}

