/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var nAvg;
var nDist;
var undefined;

include ('plot_clt_common.js');

function doParameters () {
	echo ('loc <- ' + getValue ("loc") + '; scale <- ' + getValue ("scale") + ';\n');
}

function doExpVar () {
	echo ('avg.exp <- loc;\n');
	echo ('avg.var <- ((pi^2/3)*scale^2)/' + nAvg + ';\n');
}

function doGenerateData () {
	echo ('data <- matrix(rlogis(n=' + nAvg*nDist + ', location=loc, scale=scale), nrow=' + nAvg + ');\n');
}

