/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var nAvg;
var nDist;
var undefined;

include ('plot_clt_common.js');

function doParameters () {
	echo ('df <- ' + getValue ("df") + '; ncp <- ' + getValue ("ncp") + ';\n');
}

function doExpVar () {
	if (getValue ("ncp") == 0) {

		echo ('avg.exp <- df;\n');
		echo ('avg.var <- (2*df)/' + nAvg + ';\n');
	} else {

		echo ('avg.exp <- df + ncp;\n');
		echo ('avg.var <- (2*df + 4*ncp)/' + nAvg + ';\n');
	}
}

function doGenerateData () {
	echo ('data <- matrix(rchisq(n=' + nAvg*nDist + ', df=df, ncp=ncp), nrow=' + nAvg + ');\n');
}

