/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var nAvg;
var nDist;
var undefined;

include ('plot_clt_common.js');

function doParameters () {
	echo ('prob <- ' + getValue ("prob") + ';\n');
}

function doExpVar () {
	echo ('avg.exp <- (1-prob)/prob;\n');
	echo ('avg.var <- ((1-prob)/(prob^2))/' + nAvg + ';\n');
}

function doGenerateData () {
	echo ('data <- matrix(rgeom(n=' + nAvg*nDist + ', prob=prob), nrow=' + nAvg + ');\n');
}

