/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var undefined;


function calculate () {
	var dir = "";
	dir = getValue ("dir");

	echo ('setwd("' + dir + '")\n');
}

