/***************************************************************************
                          rkwardview.h  -  description
                             -------------------
    begin                : Tue Oct 29 20:06:08 CET 2002
    copyright            : (C) 2002 by Thomas Friedrichsmeier 
    email                : tfry@users.sourceforge.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef RKWARDVIEW_H
#define RKWARDVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for Qt
#include <qwidget.h>

#include "twintable.h"

class RKwardDoc;

/** The RKwardView class provides the view widget for the RKwardApp instance.	
 * The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As RKwardView is part of the
 * docuement-view model, it needs a reference to the document object connected with it by the RKwardApp class to manipulate and display
 * the document structure provided by the RKwardDoc class.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 0.4 code generation
 */
class RKwardView : public TwinTable
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    RKwardView(QWidget *parent = 0, const char *name=0);
    /** Destructor for the main view */
    ~RKwardView();

    /** returns a pointer to the document connected to the view instance. Mind that this method requires a RKwardApp instance as a parent
     * widget to get to the window document pointer by calling the RKwardApp::getDocument() method.
     *
     * @see RKwardApp#getDocument
     */
    RKwardDoc *getDocument() const;

    /** contains the implementation for printing functionality */
    void print(QPrinter *pPrinter);
	
  private:

};

#endif // RKWARDVIEW_H
