/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var undefined;



function printout () {
	doPrintout (true);
}

function preview () {
	preprocess ();
	calculate ();
	doPrintout (false);	// only this one actually needed...
}

// internal helper functions
function doPrintout (final) {
	var densityscaled = "";
	var bw = "";
	var adjust = "";
	var narm = "";
	var n = "";
	var x = "";
	var plot_adds = "";
	densityscaled = getValue ("densityscaled");
	bw =  getValue ("bw");
	adjust = getValue ("adjust");
	narm = getValue ("narm");
	n = getValue ("n"); //calls "resolution"
	x = getValue ("x");
	plot_adds = getValue ("plotoptions.code.calculate");


	if (final) {
		echo ('rk.header ("Histogram", list ("Variable", rk.get.description (' + x + ') ');
		if ((densityscaled) && getValue ("density")) {
			echo (', "Density bandwidth", "');
			echo (bw);
			echo ('", "Density adjust", ');
			echo (adjust);
			echo (', "Density resolution", ');
			echo (n);
			echo (', "Density Remove missing values", ');
			echo (narm);
			echo (' ');
		}
		echo (' ' + getValue ("histogram_opt.code.preprocess") + '))\n');
		echo ('\n');
		echo ('rk.graph.on ()\n');
	}

	echo ('try ({\n');
	echo ('	hist (' + x + getValue ("histogram_opt.code.calculate") + getValue ("histogram_opt.code.printout") + getValue ("plotoptions.code.printout") + ')\n');
	if ((densityscaled) && getValue ("density")) {
		echo ('	lines(density(' + x + ', bw="' + bw + '", adjust = ' + adjust + ', ' + narm + ', n = ' + getValue ("n") + ')' + getValue ("col_density.code.printout") + ')\n');
	}
	if (!empty (plot_adds)) {
		echo ('\n');
		// print the grid() related code
		printIndented ("\t", plot_adds);
	}

	echo ('})\n');
	if (final) {
		echo ('rk.graph.off ()\n');
	}
}


