/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var undefined;



function printout () {
	doPrintout (true);
}

function preview () {
	preprocess ();
	calculate ();
	doPrintout (false);
}

function doPrintout (full) {
	var x = "";
	var y = "";
	var plot_adds = "";
	x = getValue ("xvarslot");
	y = getValue ("yvarslot");
	if (!(y == "")) {
		y = ", " + y;
	}
	// get additional code (as of now grid) from the calculate section
	plot_adds = getValue ("plotoptions.code.calculate");

	if (full) {

		echo ('rk.header ("Generic Plot")\n');
		echo ('rk.graph.on ()\n');
	}

	echo ('try({\n');
	echo ('	plot(' + x + y + getValue ("plotoptions.code.printout") + ');\n');
	if (!empty (plot_adds)) {
		echo ('\n');
		// print the grid() related code
		printIndented ("\t", plot_adds);
	}

	echo ('})\n');
	if (full) {

		echo ('rk.graph.off ()\n');
	}
}

