/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;



function printout () {
	var options = "";
	var addtoplot = "";
	var lty = "";
	var verticals = "";
	var do_points = "";
	var col_hor = "";
	var col_y0 = "";
	var col_y1 = "";
	options = "";

	addtoplot = getValue ("addtoplot");
	if (addtoplot) options += ', add=TRUE';

	lty = getValue ("linetype");
	if (!(lty == "")) options += ", lty=\"{$lty}\"";

	verticals = getValue ("verticals");
	if (verticals) {
		options += ', verticals=TRUE' + getValue ("col_vert.code.printout");
	} else options += ', verticals=FALSE';

	do_points = getValue ("do_points");
	if (do_points) {
		options += getValue ("col_points.code.printout");
	} else options += ', do.points=FALSE';

	col_hor = getValue ("col_hor.code.printout");
	if (!(col_hor == "")) options += getValue ("col_hor.code.printout");

	if (getValue ("allow_col01line")) {
		col_y0 = getValue ("col_y0.code.printout");
		col_y1 = getValue ("col_y1.code.printout");
		if ((col_y0 != "") && (col_y1 != "")) {
			options += ", col.01line=c({$col_y0},{$col_y1})";
		}
		elseif ((col_y0 != "") || (col_y1 != "")) {
			options += ", col.01line={$col_y0}{$col_y1}";
		} // col.01line option to plot.ecdf()
	}

	echo (options);
}

