/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:

---------------------------- */

// globals
var undefined;



function printout () {
	var x = "";
	var scale = "";
	var width = "";
	var atom = "";
	x = getValue ("x");
	scale = getValue ("scale");
	width = getValue ("width");
	atom = getValue ("atom");

	echo ('rk.header ("Stem-and-Leaf Plot",\n');
	echo ('	parameters=list ("Variable", paste (rk.get.description (' + x + ')), "Plot Length", "' + scale + '","Plot Width", "' + width + '", "Tolerance", "' + atom + '"))\n');
	echo ('\n');
	echo ('rk.print.literal(capture.output(stem(' + x + ', scale = ' + scale + ', width = ' + width + ', atom = ' + atom + ')))\n');
}

