/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	var vars = "";
	vars = str_replace ("\n", ",", trim (getValue ("x"))) ;

	echo ('data <- data.frame (' + vars + ', check.names=FALSE)\n');
	echo ('datadescription <- paste (rk.get.description (' + vars + '), collapse=", ");\n');
}

function calculate () {
	echo ('result <- ftable (data');
	if (!getValue ("exclude_nas.state")) echo (", exclude=NULL");
	echo (');\n');
}

function printout () {
	echo ('rk.header ("Crosstabs (n to n)", parameters=list ("Variables"=datadescription))\n');
	echo ('\n');
	echo ('rk.print (result)\n');
}

