/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the eRm package, so in case it's not loaded...

	echo ('  require(eRm)\n');
}


function printout () {
	doPrintout (true);
}

function preview () {
	preprocess ();
	calculate ();
	doPrintout (false);
}

function doPrintout (final) {
	var inp_items = "";
	var spin_abilfrom = "";
	var spin_abilto = "";
	var spin_probfrom = "";
	var spin_probto = "";
	var annotation = "";
	var chk_ask = "";
	var chk_mplot = "";
	var plot_options = "";
	var plot_ops_main = "";
	var plot_ops_type = "";
	var plot_ops_xlab = "";
	var plot_ops_ylab = "";
	var options = "";
	var arr_items = "";
	// this function takes care of generating the code for the printout() section. If $final is set to true,
	// it generates the full code, including headers. If $final is set to false, only the essentials will
	// be generated.

	// let's read all values into php variables for the sake of readable code
	inp_items        = getValue("inp_items");
	spin_abilfrom    = getValue("spin_abilfrom");
	spin_abilto      = getValue("spin_abilto");
	spin_probfrom    = getValue("spin_probfrom");
	spin_probto      = getValue("spin_probto");
	annotation       = getValue("annotation");
	chk_ask          = getValue("chk_ask");
	chk_mplot        = getValue("chk_mplot");

	// in case there are generic plot options defined:
	plot_options     = getValue("plotoptions.code.printout");
	plot_ops_main    = getValue("plotoptions.main");
	plot_ops_type    = getValue("plotoptions.pointtype");
	plot_ops_xlab    = getValue("plotoptions.xlab");
	plot_ops_ylab    = getValue("plotoptions.ylab");

	///////////////////////////////////
	// check for selected options
	options = new Array) ;
	// plot all items?
	if (inp_items) {
	// for user convenience, we replace "-", ";" and space, split all input into an array
	// and join it again, separated by commas:
	inp_items = str_replace("-",":",inp_items);
		arr_items = split('[ ;]', inp_items);
		options[] = "item.subset=c("+join(",", arr_items)+")";
	}
	if (chk_mplot == "mplot")
	options[] = "mplot=TRUE" ;
	if (chk_ask != "ask")
		options[] = "ask=FALSE" ;

		// more advanced options
		// user defined ranges? we'll round it to two digits
		if ((spin_abilfrom != "-4" || spin_abilto != "4") && spin_abilfrom < spin_abilto)
				options[] = "xlim=c("+round(spin_abilfrom,2)+","+round(spin_abilto,2)+")" ;
				if ((spin_probfrom != "0" || spin_probto != "1") && spin_probfrom < spin_probto)
					options[] = "ylim=c("+round(spin_probfrom,2)+","+round(spin_probto,2)+")" ;
					// annotate lines and show legend?
					if (annotation == "plain")
					options[] = "legpos=FALSE" ;

					if (final) {
						echo ('rk.header("Rating scale model plot")\n');
							echo ('\n');
							echo ('rk.graph.on()\n');
						}
	// only the following section will be generated for $final==false


	echo ('try(plotICC(' + getValue("x"));
	if (options) echo(", "+join(", ", options));
		if (plot_options) echo(plot_options);
		echo ('))\n');
		if (final) {
			echo ('rk.graph.off()\n');
			}
}
