.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RKWARD 1 "11-10-2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rkward \(hy A KDE frontend to R
.SH SYNOPSIS
.B rkward
.RI [ options ] " [file]"
.SH DESCRIPTION
This manual page documents briefly the
.B rkward
command.
.PP
.SH OPTIONS
A summary of options is included below.
For a complete description, invoke rkward \-\-help or refer to http://rkward.sourceforge.net .
.TP
.B \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-\-evaluate <Rcode>
The given R code is evaluated after RKWard has started, and after any specified workspace is loaded. Mostly useful for automated testing.
.TP
.B \-\-debug-level <level>
Verbosity of debug output. 0-5, where 0 is no output, 5 is all output including function trace information. Default it 2
.TP
.B \-\-debug-flags <flags>
Allows to configure, which sections of code to debug. Flags are given as a binary number. Refer to the source files for documentation, as this really is an internal option
.TP
.B \-\-debugger <command>
Run RKWard through the specified debugger command. To add command line options to the debugger command, enclose them in single quotes ('') together with the command.
.TP
.B \-\-disable-stack-check
Disable the R C stack checking mechanism. If you see the error message "C stack usage too close to the limit", this option may serve as a workaround.
.SH SEE ALSO
.BR R (1),
.br
.SH AUTHOR
RKWard was written by Thomas Friedrichsmeier and the RKWard team. See http://rkward.sourceforge.net .
.PP
This manual page was written by Thomas Friedrichsmeier <tfry@users.sourceforge.net>,
for the Debian project (but may be used by others).
