/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var constraint = "";
	var startval = "";
	var startval_mtx = "";
	var naaction = "";
	var irtparam = "";
	var optimeth = "";
	var verbose = "";
	var ghk_rasch = "";
	var iterqn_rasch = "";
	var control = "";
	// let's read all values into php variables for the sake of readable code
	constraint   = getValue("constraint");
	startval     = getValue("startval");
	startval_mtx = getValue("startval_mtx");
	naaction     = getValue("naaction");
	irtparam     = getValue("irtparam");
	optimeth     = getValue("optimeth");
	verbose      = getValue("verbose");
	// these are rasch specific
	ghk_rasch    = getValue("ghk_rasch");
	iterqn_rasch = getValue("iterqn_rasch");

	///////////////////////////////////
	// check for selected advanced control options
	control = new Array) ;
	if (iterqn_rasch != "150")
	control[] = "iter.qN="+iterqn_rasch ;
	if (ghk_rasch != "21")
		control[] = "GHk="+ghk_rasch ;
		if (optimeth != "BFGS")
			control[] = "method=\""+optimeth+"\"" ;
			if (verbose == "TRUE")
				control[] = "verbose=TRUE" ;

				echo ('estimates.rasch <- rasch(' + getValue("x"));
					// any additional options?
					if (constraint) echo(", constraint="+constraint);
					if (irtparam != "TRUE") echo(", IRT.param=FALSE");
						if (startval == "random") echo(", start.val=\"random\"");
							if (startval == "matrix") echo(", start.val="+startval_mtx);
								if (naaction) echo(", na.action="+naaction);
									// finally check if any advanced control options must be inserted
									if (control) echo(", control=list("+join(", ", control)+")");
											echo (')\n');
										}

function printout () {
	var save = "";
	var save_name = "";
	var irtparam = "";
	// check whether parameter estimations should be kept in the global enviroment
	save         = getValue("chk_save");
	save_name    = getValue("save_name");
	irtparam     = getValue("irtparam");

	echo ('rk.header ("Rasch parameter estimation")\n');
	echo ('rk.print (paste("Call: <code>",deparse(estimates.rasch$call, width.cutoff=500),"</code>"))\n');
	echo ('rk.print ("<h4>Coefficients:</h4>")\n');
	echo ('rk.print (coef(estimates.rasch))\n');
	echo ('rk.print (paste("Log-likelihood value at convergence:",round(estimates.rasch$log.Lik, digits=1)))\n');
// check if results are to be saved:
	if (save && save_name) {

		echo ('# keep results in current workspace\n');
		echo (save_name + ' <<- estimates.rasch\n');
	}
}
