/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var constraint = "";
	var startval = "";
	var startval_mtx = "";
	var naaction = "";
	var irtparam = "";
	var optimeth = "";
	var verbose = "";
	var ghk_2pl = "";
	var iterem = "";
	var iterqn_2pl = "";
	var interact = "";
	var control = "";
	// let's read all values into php variables for the sake of readable code
	constraint   = getValue("constraint");
	startval     = getValue("startval");
	startval_mtx = getValue("startval_mtx");
	naaction     = getValue("naaction");
	irtparam     = getValue("irtparam");
	optimeth     = getValue("optimeth");
	verbose      = getValue("verbose");
	// these are 2pl specific
	ghk_2pl      = getValue("ghk_2pl");
	iterem       = getValue("iterem");
	iterqn_2pl   = getValue("iterqn_2pl");
	interact     = getValue("interact");

	///////////////////////////////////
	// check for selected advanced control options
	control = new Array) ;
	if (iterem != "40")
	control[] = "iter.em="+iterem ;
	if (iterqn_2pl != "150")
		control[] = "iter.qN="+iterqn_2pl ;
		if (ghk_2pl != "15")
			control[] = "GHk="+ghk_2pl ;
			if (optimeth != "BFGS")
				control[] = "method=\""+optimeth+"\"" ;
				if (verbose == "TRUE")
					control[] ="verbose=TRUE" ;

					echo ('estimates.2pl <- ltm(' + getValue("x") + ' ~ z1');
						// any additional options?
						if (interact == "TRUE") echo(" * z2");
						if (constraint) echo(", constraint="+constraint);
							if (irtparam != "TRUE") echo(", IRT.param=FALSE");
								if (startval == "random") echo(", start.val=\"random\"");
									if (startval == "matrix") echo(", start.val="+startval_mtx);
										if (naaction) echo(", na.action="+naaction);
											// finally check if any advanced control options must be inserted
											if (control) echo(", control=list("+join(", ", control)+")");
													echo (')\n');
												}

function printout () {
	var save = "";
	var save_name = "";
	// check whether parameter estimations should be kept in the global enviroment
	save         = getValue("chk_save");
	save_name    = getValue("save_name");

	echo ('rk.header ("2PL parameter estimation")\n');
	echo ('rk.print (paste("Call: <code>",deparse(estimates.2pl$call, width.cutoff=500),"</code>"))\n');
	echo ('rk.print ("<h4>Coefficients:</h4>")\n');
	echo ('rk.print (coef(estimates.2pl))\n');
	echo ('rk.print (paste("Log-likelihood value at convergence:",round(estimates.2pl$log.Lik, digits=1)))\n');
// check if results are to be saved:
	if (save && save_name) {

		echo ('# keep results in current workspace\n');
		echo (save_name + ' <<- estimates.2pl\n');
	}
}
