/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var constraint = "";
	var startval = "";
	var startval_mtx = "";
	var naaction = "";
	var irtparam = "";
	var optimeth = "";
	var verbose = "";
	var ghk_3pl = "";
	var iterqn_3pl = "";
	var type = "";
	var maxguess = "";
	var optimizer = "";
	var epshess = "";
	var control = "";
	// let's read all values into php variables for the sake of readable code
	constraint   = getValue("constraint");
	startval     = getValue("startval");
	startval_mtx = getValue("startval_mtx");
	naaction     = getValue("naaction");
	irtparam     = getValue("irtparam");
	optimeth     = getValue("optimeth");
	verbose      = getValue("verbose");
	// these are 3pl specific
	ghk_3pl      = getValue("ghk_3pl");
	iterqn_3pl   = getValue("iterqn_3pl");
	type         = getValue("type");
	maxguess     = getValue("maxguess");
	optimizer    = getValue("optimizer");
	epshess      = getValue("epshess");
	// $parscale     = getRK_val("parscale"); not implemented yet...

	///////////////////////////////////
	// check for selected advanced control options
	control = new Array) ;
	if (optimizer != "optim")
	control[] = "optimizer=\"nlminb\"" ;
	if (iterqn_3pl != "1000")
		control[] = "iter.qN="+iterqn_3pl ;
		if (ghk_3pl != "21")
			control[] = "GHk="+ghk_3pl ;
			if (optimizer == "optim" && optimeth != "BFGS")
				control[] = "method=\""+optimeth+"\"" ;
				if (verbose == "TRUE")
					control[] = "verbose=TRUE" ;
					if (epshess != "1e-03")
						control[] = "eps.hessian="+epshess ;

						echo ('estimates.3pl <- tpm(' + getValue("x"));
							// any additional options?
							if (type == "rasch") echo(", type=\"rasch\"");
							if (constraint) echo(", constraint="+constraint);
								if (maxguess != "1") echo(", max.guessing="+maxguess);
									if (irtparam != "TRUE") echo(", IRT.param=FALSE");
										if (startval == "random") echo(", start.val=\"random\"");
											if (startval == "matrix") echo(", start.val="+startval_mtx);
												if (naaction) echo(", na.action="+naaction);
													// finally check if any advanced control options must be inserted
													if (control) echo(", control=list("+join(", ", control)+")");
															echo (')\n');
														}

function printout () {
	var save = "";
	var save_name = "";
	// check whether parameter estimations should be kept in the global enviroment
	save         = getValue("chk_save");
	save_name    = getValue("save_name");

	echo ('rk.header ("3PL parameter estimation")\n');
	echo ('rk.print (paste("Call: <code>",deparse(estimates.3pl$call, width.cutoff=500),"</code>"))\n');
	echo ('rk.print ("<h4>Coefficients:</h4>")\n');
	echo ('rk.print (coef(estimates.3pl))\n');
	echo ('rk.print (paste("Log-likelihood value at convergence:",round(estimates.3pl$log.Lik, digits=1)))\n');
// check if results are to be saved:
	if (save && save_name) {

		echo ('# keep results in current workspace\n');
		echo (save_name + ' <<- estimates.3pl\n');
	}
}
