/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var constraint = "";
	var startval = "";
	var startval_lst = "";
	var hessian = "";
	var naaction = "";
	var irtparam = "";
	var optimeth = "";
	var verbose = "";
	var ghk_grm = "";
	var iterqn_grm = "";
	var dig_abbrv = "";
	var control = "";
	// let's read all values into php variables for the sake of readable code
	constraint   = getValue("constraint");
	startval     = getValue("startval");
	startval_lst = getValue("startval_lst");
	hessian      = getValue("hessian");
	naaction     = getValue("naaction");
	irtparam     = getValue("irtparam");
	optimeth     = getValue("optimeth");
	verbose      = getValue("verbose");
	// these are grm specific
	ghk_grm      = getValue("ghk_grm");
	iterqn_grm   = getValue("iterqn_grm");
	dig_abbrv    = getValue("dig_abbrv");

	///////////////////////////////////
	// check for selected advanced control options
	control = new Array) ;
	if (iterqn_grm != "150")
	control[] = "iter.qN="+iterqn_grm ;
	if (ghk_grm != "21")
		control[] = "GHk="+ghk_grm ;
		if (optimeth != "BFGS")
			control[] = "method=\""+optimeth+"\"" ;
			if (verbose == "TRUE")
				control[] = "verbose=TRUE" ;
				if (dig_abbrv != "6")
					control[] = "digits.abbrv="+dig_abbrv ;

					echo ('estimates.grm <- grm(' + getValue("x"));
						// any additional options?
						if (constraint == "const_discr") echo(", constrained=TRUE");
						if (irtparam != "TRUE") echo(", IRT.param=FALSE");
							if (hessian == "hessian") echo(", Hessian=TRUE");
								if (startval == "random") echo(", start.val=\"random\"");
									if (startval == "list") echo(", start.val="+startval_lst);
										if (naaction) echo(", na.action="+naaction);
											// finally check if any advanced control options must be inserted
											if (control) echo(", control=list("+join(", ", control)+")");
													echo (')\n');
												}

function printout () {
	var save = "";
	var save_name = "";
	// check whether parameter estimations should be kept in the global enviroment
	save         = getValue("chk_save");
	save_name    = getValue("save_name");

	echo ('rk.header ("GRM parameter estimation")\n');
	echo ('rk.print (paste("Call: <code>",deparse(estimates.grm$call, width.cutoff=500),"</code>"))\n');
	echo ('rk.print ("<h4>Coefficients:</h4>")\n');
	echo ('rk.print (coef(estimates.grm))\n');
	echo ('rk.print (paste("Log-likelihood value at convergence:",round(estimates.grm$log.Lik, digits=1)))\n');
// check if results are to be saved:
	if (save && save_name) {

		echo ('# keep results in current workspace\n');
		echo (save_name + ' <<- estimates.grm\n');
	}
}
