/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the eRm package, so in case it's not loaded...

	echo ('  require(eRm)\n');
}

function calculate () {
	var rad_splitcr = "";
	var splitvector = "";
	// let's read all values into php variables for the sake of readable code
	rad_splitcr    = getValue("rad_splitcr");
	splitvector     = getValue("splitvector");

	echo ('waldtest.res <- Waldtest(' + getValue("x"));
	// check if any advanced control options must be inserted
	if (rad_splitcr == "mean") echo(", splitcr=\"mean\"") ;
	if (rad_splitcr == "vector") echo(", splitcr="+splitvector) ;
	echo (')\n');
}

function printout () {
	echo ('rk.header ("Wald test (' + getValue("x") + ')")\n');
	echo ('rk.print (waldtest.res)\n');
}
