/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var spin_groups = "";
	var drop_sumgroups = "";
	var rad_pvalue = "";
	var spin_mc = "";
	var options = "";
	// let's read all values into php variables for the sake of readable code
	spin_groups     = getValue("spin_groups");
	drop_sumgroups  = getValue("drop_sumgroups");
	rad_pvalue      = getValue("rad_pvalue");
	spin_mc         = getValue("spin_mc");

	///////////////////////////////////
	// check for selected options
	options = new Array) ;
	if (spin_groups != "10")
	options[] = "G=$spin_groups" ;
	if (drop_sumgroups != "median")
		options[] = "FUN=$drop_sumgroups" ;
		if (rad_pvalue == "montecarlo")
			options[] = "simulate.p.value=TRUE" ;
			if (rad_pvalue == "montecarlo" && spin_mc != "100" )
				options[] = "B=$spin_mc" ;


				echo ('itemfit.res <- item.fit(' + getValue("x"));
					// check if any advanced control options must be inserted
					if (options) echo(", "+join(", ", options));
						echo (')\n');
					}

function printout () {
	echo ('rk.header ("Item-fit statistics (' + getValue("x") + ')")\n');
	echo ('rk.print (itemfit.res)\n');
}
