/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var rad_hypot = "";
	var rad_resppat = "";
	var mtx_resppat = "";
	var rad_pvalue = "";
	var spin_mc = "";
	var options = "";
	// let's read all values into php variables for the sake of readable code
	rad_hypot       = getValue("rad_hypot");
	rad_resppat     = getValue("rad_resppat");
	mtx_resppat     = getValue("mtx_resppat");
	rad_pvalue      = getValue("rad_pvalue");
	spin_mc         = getValue("spin_mc");

	///////////////////////////////////
	// check for selected options
	options = new Array) ;
	if (rad_hypot == "greater" || rad_hypot == "two.sided")
	options[] = "alternative=\"$rad_hypot\"" ;
	if (rad_resppat == "resp_matrix" && mtx_resppat)
		options[] = "resp.patterns=$mtx_resppat" ;
		if (rad_pvalue == "montecarlo")
			options[] = "simulate.p.value=TRUE" ;
			if (rad_pvalue == "montecarlo" && spin_mc != "1000" )
				options[] = "B=$spin_mc" ;


				echo ('personfit.res <- person.fit(' + getValue("x"));
					// check if any advanced control options must be inserted
					if (options) echo(", "+join(", ", options));
						echo (')\n');
					}

function printout () {
	echo ('rk.header ("Person-fit statistics (' + getValue("x") + ')")\n');
	echo ('rk.print (personfit.res)\n');
}
