/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var data = "";
	var chk_select = "";
	var inp_items = "";
	var spin_samples = "";
	var chk_standard = "";
	var chk_na = "";
	var chk_bsci = "";
	var spin_ci = "";
	var options = "";
	var cilo = "";
	var cihi = "";
	// let's read all values into php variables for the sake of readable code
	data            = getValue("x");
	chk_select      = getValue("chk_select");
	inp_items       = getValue("inp_items");
	spin_samples    = getValue("spin_samples");
	chk_standard    = getValue("chk_standard");
	chk_na          = getValue("chk_na");
	chk_bsci        = getValue("chk_bsci");
	spin_ci         = getValue("spin_ci");

	// reformat $inp_items
	if (inp_items)
		inp_items       = str_replace("\n", ", ", preg_replace("/(.+)\[\[(.+)\]\]/", "$2", inp_items));

	///////////////////////////////////
	// check for selected options
	options = new Array) ;
	if (chk_standard == "standard")
	options[] = "standardized=TRUE" ;
	if (chk_bsci == "bsci")
		options[] = "CI=TRUE" ;
		if (spin_ci != ".95") {
			cilo = (1-spin_ci)/2 ;
				cihi = 1-cilo ;
				options[] = "probs=c($cilo, $cihi)" ;
			}
	if (spin_samples != "1000")
	options[] = "B=$spin_samples" ;
	if (chk_na == "rm")
		options[] = "na.rm=TRUE" ;


		echo ('cronalpha.res <- cronbach.alpha(');
		if (data && chk_select && inp_items)
			echo ("subset("+data+", select=c("+inp_items+"))");
					else
						echo (data);
						// check if any advanced control options must be inserted
						if (options) echo(", "+join(", ", options));
								echo (')\n');
								echo ('descript.res <- descript(');
								if (data && chk_select && inp_items)
								echo ("subset("+data+", select=c("+inp_items+"))");
								else
									echo (data);
									echo (', chi.squared=FALSE, B=' + spin_samples + ')\n');
								}

function printout () {
	var chk_select = "";
	var spin_samples = "";
	var chk_standard = "";
	var chk_na = "";
	var chk_bsci = "";
	var spin_ci = "";
	var inp_items = "";
	chk_select      = getValue("chk_select");
	spin_samples    = getValue("spin_samples");
	chk_standard    = getValue("chk_standard");
	chk_na          = getValue("chk_na");
	chk_bsci        = getValue("chk_bsci");
	spin_ci         = getValue("spin_ci");
	inp_items       = getValue("inp_items");
	// reformat $inp_items
	if (inp_items)
		inp_items       = str_replace("\n", ", ", preg_replace("/(.+)\[\[\"(.+)\"\]\]/", "$2", inp_items));

	echo ('rk.header ("Cronbach\'s alpha")\n');
	echo ('rk.print("for the \'' + getValue("x") + '\' data-set');
	if (chk_select && inp_items)
		echo (" (subset: "+inp_items+")");
	echo ('")\n');
	echo ('rk.print(paste("Items:",cronalpha.res$p,"<br />Sample units:",cronalpha.res$n,"<br /><strong>alpha:",round(cronalpha.res$alpha, digits=2),"</strong>');
	if (chk_standard) echo(" (standardized)");
	echo ('"))\n');
	echo ('rk.print("Effects on alpha if items are removed:")\n');
	echo ('rk.print(descript.res$alpha)\n');
	if (chk_bsci) {
		echo ('rk.print("' + (spin_ci * 100)+"%" + ' Confidence interval:")\n');
		echo ('rk.print(cronalpha.res$ci)\n');
	}
}
