/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: '$' inside '"'-delimited string. This might be a variable name. Please check by hand!
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;

function preprocess () {
	// we'll need the ltm package, so in case it's not loaded...

	echo ('  require(ltm)\n');
}

function calculate () {
	var spin_samples = "";
	// let's read all values into php variables for the sake of readable code
	spin_samples    = getValue("spin_samples");

	echo ('unidim.res <- unidimTest(' + getValue("x"));
	// check if any options must be inserted
	if (spin_samples != "100") echo(", B=$spin_samples") ;
	echo (')\n');
}

function printout () {
	var save = "";
	var save_name = "";
	save         = getValue("chk_save");
	save_name    = getValue("save_name");

	echo ('rk.header ("Unidimensionality check (' + getValue("x") + ')")\n');
	echo ('rk.print (unidim.res)\n');
// check if results are to be saved:
	if (save && save_name) {

		echo ('# keep results in current workspace\n');
		echo (save_name + ' <<- unidim.res\n');
	}
}
