# - This file is part of the RKWard project (https://rkward.kde.org).
# SPDX-FileCopyrightText: by Thomas Friedrichsmeier <thomas.friedrichsmeier@kdemail.net>
# SPDX-FileContributor: The RKWard Team <rkward-devel@kde.org>
# SPDX-License-Identifier: GPL-2.0-or-later
# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{rkward}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab rkward\cr
#' Type: \tab Package\cr
#' Version: \tab 0.8.0\cr
#' Date: \tab 2024-07-18\cr
#' Depends: \tab R (>= 2.9.0),methods\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 2)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://rkward.kde.org\cr
#' }
#'
#' @title
#' \packageTitle{rkward}
#' @author
#' \packageAuthor{rkward}
#'
#' Maintainer: \packageMaintainer{rkward}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL
