/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: please check correctness of conversion of '=>' in arrays by hand
Warning: please check correctness of conversion of '=>' in arrays by hand

---------------------------- */

// globals
var undefined;


function calculate () {
	var vars = "";
	vars = str_replace ("\n", "','", trim (getValue ("data"))) ;

	echo ('package.skeleton(name="' + getValue("name") + '", list=c(\'' + vars + '\'), path="' + getValue("path") + '", force= ' + getValue("force") + ')\n');
}

function printout () {
	makeHeaderCode ("Create package skeleton", new Array("Name" ,  getValue ("name"), "Directory" ,  getValue ("path")));
}

