<document>
	<about
		name="RKWard pluginmap"
		shortinfo="Part of the official RKWard distribution"
		version="0.6.1"
		license="GPL"
		url="http://rkward.sf.net">
		<author
			name="RKWard Team"
			email="rkward-devel@lists.sf.net"
			url="http://rkward.sf.net" />
	</about>
	<!-- Guard against accidental inclusion of pluginmaps in a different installed version of RKWard -->
	<dependencies rkward_min_version="0.6.1" rkward_max_version="0.6.1y" />
</document>
 
