<document>
	<about
		name="RKWard pluginmap"
		shortinfo="Part of the official RKWard distribution"
		version="0.6.3"
		license="GPL"
		url="http://rkward.kde.org">
		<author
			name="RKWard Team"
			email="rkward-devel@lists.sf.net"
			url="http://rkward.kde.org" />
	</about>
	<!-- Guard against accidental inclusion of pluginmaps in a different installed version of RKWard -->
	<dependencies rkward_min_version="0.6.2z" rkward_max_version="0.6.3y" />
</document>
 
