# find the R binary

MESSAGE(STATUS "Looking for R executable")
IF(R_EXECUTABLE)
	MESSAGE(STATUS "Specified by user")
ENDIF(R_EXECUTABLE)
FIND_PROGRAM(R_EXECUTABLE R)

IF(R_EXECUTABLE-NOTFOUND)
	MESSAGE(FATAL_ERROR "Could NOT find R (TODO: name option)")
ELSE(R_EXECUTABLE-NOTFOUND)
	MESSAGE(STATUS "Using R at ${R_EXECUTABLE}")
ENDIF(R_EXECUTABLE-NOTFOUND)

# CPP flags

MESSAGE(STATUS "Quering R for CPP flags")
IF(NOT R_CPPFLAGS)
	EXEC_PROGRAM(${R_EXECUTABLE}
		ARGS CMD config --cppflags
		OUTPUT_VARIABLE R_CPPFLAGS)
ELSE(NOT R_CPPFLAGS)
	MESSAGE(STATUS "Overridded by user")
ENDIF(NOT R_CPPFLAGS)
IF(NOT R_CPPFLAGS)
	MESSAGE(STATUS "CPP flags are empty. This looks suspicious, but we'll proceed...")
ELSE(NOT R_CPPFLAGS)
	MESSAGE(STATUS "CPP flags are '${R_CPPFLAGS}'")
ENDIF(NOT R_CPPFLAGS)

# LD flags

MESSAGE(STATUS "Quering R for LD flags")
IF(NOT R_LDFLAGS)
	EXEC_PROGRAM(${R_EXECUTABLE}
		ARGS CMD config --ldflags
		OUTPUT_VARIABLE R_LDFLAGS)
ELSE(NOT R_LDFLAGS)
	MESSAGE(STATUS "Overridded by user")
ENDIF(NOT R_LDFLAGS)
IF(NOT R_LDFLAGS)
	MESSAGE(STATUS "LD flags are empty. This looks suspicious, but we'll proceed...")
ELSE(NOT R_LDFLAGS)
	MESSAGE(STATUS "LD flags are '${R_LDFLAGS}'")
ENDIF(NOT R_LDFLAGS)

# TODO: perhaps we should try to compile a simple prog at this point?

# find R package library location

MESSAGE(STATUS "Checking for R package library location to use")
IF(NOT R_LIBDIR)
	EXEC_PROGRAM(${R_EXECUTABLE}
		ARGS CMD sh -c 'echo $R_LIBS:$R_LIBS_SITE'
		OUTPUT_VARIABLE R_LIBDIR)
ELSE(NOT R_LIBDIR)
	MESSAGE(STATUS "Location specified by user")
ENDIF(NOT R_LIBDIR)

# strip whitespace
STRING(REGEX REPLACE "[ \n]+"
	"" R_LIBDIR
	"${R_LIBDIR}")

# strip leading colon(s)
STRING(REGEX REPLACE "^:+"
	"" R_LIBDIR
	"${R_LIBDIR}")

# strip trailing colon(s)
STRING(REGEX REPLACE ":+$"
	"" R_LIBDIR
	"${R_LIBDIR}")

# find first path
STRING(REGEX REPLACE ":"
	" " R_LIBDIR
	"${R_LIBDIR}")

IF(NOT R_LIBDIR)
	MESSAGE(STATUS "Not detected and not specified.")
ENDIF(NOT R_LIBDIR)

SET(R_LIBDIRS ${R_LIBDIR})
SEPARATE_ARGUMENTS(R_LIBDIRS)

SET(R_LIBDIR)
FOREACH(CURRENTDIR ${R_LIBDIRS})
	IF(NOT USE_R_LIBDIR)
		IF(EXISTS ${CURRENTDIR})
			SET(R_LIBDIR ${CURRENTDIR})
			SET(USE_R_LIBDIR 1)
		ELSE(EXISTS ${CURRENTDIR})
			MESSAGE(STATUS "${CURRENTDIR} does not exist. Skipping")
		ENDIF(EXISTS ${CURRENTDIR})
	ENDIF(NOT USE_R_LIBDIR)
ENDFOREACH(CURRENTDIR ${R_LIBDIRS})

IF(NOT EXISTS ${R_LIBDIR})
	MESSAGE(FATAL_ERROR "No existing library location found")
ELSE(NOT EXISTS ${R_LIBDIR})
	MESSAGE(STATUS "Will use ${R_LIBDIR}")
ENDIF(NOT EXISTS ${R_LIBDIR})
