/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: please check correctness of conversion of '=>' in arrays by hand
Warning: please check correctness of conversion of '=>' in arrays by hand
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;


function calculate () {
	echo ('write.table ( x =  ' + getValue("data") + ' , file =  "' + getValue("file") + '" , append =  ' + getValue("append") + '  ,quote = ' + getValue("quote")) echo (' ,  sep = ' + getValue("sep")) echo (' , eol = "' + getValue("eol"))  echo ('" , na = "' + getValue("na"))  echo ('" ,  dec = ' + getValue("dec")) echo (' , row.names =  ');
	if (getValue("rows") == "custoRow") echo (getValue("rownames")) ;
	else  echo (getValue("rows") + ' ,  col.names =  ');
	if (getValue("columns") == "custoCol") echo (getValue("colnames")) ;
	else  echo (getValue("columns") + ' , qmethod=  ' + getValue("qmethod") + ' ) \n');
}

function printout () {
	makeHeaderCode ("Write as table", new Array("File" ,  getValue ("file"), "Data" ,  getValue ("data")));
}

