/* ------- This file generated by php2js from PHP code. --------
Please check this file by hand, and remove this notice, afterwards.
Messages:
Warning: please check correctness of conversion of '=>' in arrays by hand
Warning: please check correctness of conversion of '=>' in arrays by hand
Note: Control statement without braces. This is bad style.
Note: Control statement without braces. This is bad style.

---------------------------- */

// globals
var undefined;


function calculate () {
	var sep = "";
	sep = getValue ("sep");
	if (sep == "other") sep = getValue ("custom_sep");
	if (sep == " ") sep = "";
	else sep = ", sep=" + quote (sep);

	echo ('write (x=' + getValue("data") + ', file="' + getValue("file") + '", ncolumns=' + getValue("ncolumns") + ', append=' + getValue("append") + sep + ')\n');
}

function printout () {
	makeHeaderCode ("Write Variables", new Array("File" ,  getValue ("file"), "Data" ,  getValue ("data")));
}

